source 'https://rubygems.org'

gem 'pry'

gem 'cuba'
gem 'activerecord'
gem 'activerecord-jdbcpostgresql-adapter', '1.2.2.1'
gem 'jdbc-postgres'
#gem 'activerecord-jdbcmysql-adapter'
#gem 'jdbc-mysql'


gem 'torquebox', '2.3.0'
gem 'torquebox-server', '2.3.0'
#gem 'torquebox-console'

